server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:1111/eureka}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/cliente/**
        - id: curso-service
          uri: lb://curso-service
          predicates:
            - Path=/curso/**  

